package com.isums.notificationservice.domains.enums;

public enum NotificationCategory {
    CONTRACT_EXPIRED,
    INSPECTION_DONE,
    CONTRACT_READY_FOR_LANDLORD_SIGNATURE,
    CONTRACT_COMPLETED,
    CONTRACT_CANCELLED_BY_TENANT,
    ISSUE_WORK_SLOT_CREATED,
    ISSUE_QUOTE_WAITING_MANAGER_APPROVAL,
    RENEWAL_REQUEST,
    PAYMENT_OVERDUE,
    DEPOSIT_REFUND_CONFIRM
}
