# Eureka - disabled
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# JWT production
spring.security.oauth2.resource-server.jwt.issuer-uri=https://sso.isums.pro/realms/isums

# Kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}

# gRPC client - Service Connect DNS
spring.grpc.client.channels.user.address=dns:///user-service:1012
spring.grpc.client.channels.user.negotiation-type=plaintext

# OAuth2 client token endpoint
spring.security.oauth2.client.provider.keycloak.token-uri=https://sso.isums.pro/realms/isums/protocol/openid-connect/token

# Log
spring.jpa.show-sql=false