eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

spring.security.oauth2.resource-server.jwt.issuer-uri=https://sso.isums.pro/realms/isums

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}

spring.grpc.client.channels.user.address=dns:///user-service:1012
spring.grpc.client.channels.user.negotiation-type=plaintext

spring.security.oauth2.client.registration.user-service-client.provider=keycloak
spring.security.oauth2.client.registration.user-service-client.client-id=notification-service
spring.security.oauth2.client.registration.user-service-client.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.user-service-client.scope=openid
spring.security.oauth2.client.provider.keycloak.token-uri=https://sso.isums.pro/realms/isums/protocol/openid-connect/token

app.mail.from=noreply@isums.pro
app.mail.fromName.vi_VN=H\u1EC7 th\u1ED1ng ISUMS
app.mail.fromName.en_US=ISUMS System
app.mail.fromName.ja_JP=ISUMS\u30B7\u30B9\u30C6\u30E0

spring.jpa.show-sql=false
